### ISSUE TITLE
Unknown plugin "transform-replace-object-assign" in rheostat/.babelrc

### ISSUE THREAD

**Issue by njt1982** [airbnb/rheostat#102]
Getting this error after doing a `yarn add rheostat`...

![image](https://user-images.githubusercontent.com/384976/29046161-23a00226-7bbe-11e7-89ce-d7dbf4062b4e.png)

Seems to be the same error as on https://github.com/airbnb/react-dates/issues/530 where @ljharb suggests that we shouldn't be using babel to transpile the node_modules folder, which sounds sensible. However, I don't know how "not" to do that and I suspect that I am not the only one. I've not consciously made Babel do this, so it seems to be how some of the default templates are setup.

Also, these two Airbnb projects appear to be the top ranking ones for this error, so I do wonder if the issue is more rooted in how this package is setup? I've not experienced this with any other packages....

**Comment by njt1982** [comment]
`yarn add babel-plugin-transform-replace-object-assign` -- this did not resolve the error either.

**Comment by njt1982** [comment]
After adding the plugin, I tried adding it to my project's `.babelrc` plugins list

```
{
  "presets": ["react-native"],
  "plugins": ["transform-replace-object-assign"],
  "env": {
    "production": {
      "plugins": ["transform-remove-console"]
    }
  }
}
```

Now the error is:
```
error: bundling: Error: Couldn't find preset "airbnb" relative to directory "/Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat"
    at /Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
TransformError: /Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat/lib/Slider.js: Couldn't find preset "airbnb" relative to directory "/Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat"
Bundling `index.ios.js`  86.3% (1174/1264), failed.
error: bundling: Error: Couldn't find preset "airbnb" relative to directory "/Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat"
    at /Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/nthompson/Documents/react-native/REDACTED/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
TransformError: /Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat/lib/Slider.js: Couldn't find preset "airbnb" relative to directory "/Users/nthompson/Documents/react-native/REDACTED/node_modules/rheostat"
```

**Comment by njt1982** [comment]
Ok, there is clearly something wrong with either this package or my setup ;) 

I have got my app working but only by running `yarn install --no-lockfile` inside the rheostat folder in the node_modules folder?!

**Comment by njt1982** [comment]
Lovely... Now getting this:

![image](https://user-images.githubusercontent.com/384976/29047450-a26284c6-7bc3-11e7-9abb-c5aabb1b6574.png)

Think I'll move on to an alternative package...

**Comment by ljharb** [comment]
Are you perhaps using babel to transpile node_modules, and getting issues because you're including our babelrc?

**Comment by ljharb** [comment]
All of the dependencies you're getting complaints about are dev deps, so they shouldn't be coming up at all.

**Comment by ljharb** [comment]
(It looks like you're using react-native, which has the horrible advice of transpiling node_modules; if you're going to do that, you have to manually remove all `.babelrc` files on postinstall)

**Comment by njt1982** [comment]
I am indeed using React Native. 😊

Thanks for the response. Much appreciated. 

Why are the Airbnb package seemingly the only ones that suffer this bad advice?

**Comment by ljharb** [comment]
Many packages publish `.babelrc` files. It's likely that you've just been lucky, and only consumed packages that npmignore babelrc files.

This is a bug in the react-native packager, and it's not on individual packages to fix it. You can add a `postinstall` script to your app that removes them, however.

**Comment by dev-hamid** [comment]
are you using the rheostat with RN app? 
if so could you give me some hints how ?
